config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'
  resources :contacts, only: [:new, :create]
  resources :projects
  resources :tags
  resources :posts
  get "/about" => "welcome#about"
  get "/missing" => "welcome#missing"
  
  get '*path' => redirect('/missing')
  
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :posts
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, validate: true
    attribute :email, validate: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    attribute :message, validate: true
    attribute :nickname, captcha: true
    
    def headers 
        {
            :subject => "Contact Form",
            :to => "christophervundi@gmail.com",
            :from => %["\"#{name}\" \"<#{email}>\""]
        }
    end
    
    
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_attached_file :image, styles: { medium: "750x500>", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_presence :image
end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :project_tags
    has_many :tags, through: :project_tags
    has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    validates_attachment_presence :image
    belongs_to :user
    
    def all_tags
      project_tags.map(&:tag)
    end

    def tag_ids_to_array
      all_tags.inject([]){|tag_array, tag| tag_array << tag.id}
    end
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base
    belongs_to :project
    belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :project_tags
    has_many :projects, through: :project_tags
    
    def self.all_sass
      where(:name => "saas")
    end
    
    def self.all_mobile
      where(:name => "mobile_app")
    end
    
    def self.all_websites
      where(:name => "website") 
    end
    
    def self.all_startups
      where(:name => "startup")
    end
    
    def self.all_agencies
      where(:name => "agency")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def footer
    @fposts = Post.order("created_at DESC").limit(2)
  end
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
            flash.now[:error] = nil
        else
            flash.now[:error] = "Canot send message."
            render :new
        end
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
        if params[:category].blank?
            @posts = Post.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @posts = Post.where(category_id: @category_id).order("created_at DESC")
        end
  end
  
  def new
   @post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save 
      flash[:success] = "Post was successfully created Chris"
      redirect_to @post
    else
      render :new
      flash[:danger] = "Seems something went wrong please try again"
    end
  end

  def show
    @posts = Post.order('created_at DESC').limit(4)
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to @post
      flash[:success] = "Post was successfully updated"
    else
      render :edit
      flash[:danger] = "Ooops something went wrong..please try again"
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
  
  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :find_project, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
  
    def index
      @projects = Project.all.order('created_at DESC')#.paginate(:page => params[:page], :per_page => 5)
    end
    
    def new
     @project = current_user.projects.build
    end
    
    def create
      @project = current_user.projects.build(project_params)
      if @project.save 
        flash[:success] = "Project was successfully created Chris"
        redirect_to @project
      else
        render :new
        flash[:danger] = "Seems something went wrong please try again"
      end
    end

    def show
    end
    
    def edit
    end
    
    def update
      if @project.update(project_params)
        redirect_to @project
        flash[:success] = "project was successfully updated"
      else
        render :edit
        flash[:danger] = "Ooops something went wrong..please try again"
      end
    end
  
    def destroy
      @project.destroy
      redirect_to projects_path
    end
    
    private
    
    def project_params
      params.require(:project).permit(:title, :category, :client, :work_done, :link, :challenge, :project_goals, :solution, :results, :client_testimonial, :image)
    end
    
    def find_project
      @project = Project.find(params[:id])
    end
    
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def new
    @tag = Tag.new
    end
    
    def create
    @tag = Tag.new(tag_params)
        if @tag.save
          flash[:success] = "Tag was successfully created"
          redirect_to root_path
        else
          render :new
        end
    end
  
    def show
    @tag = Tag.find(params[:id])
    @projects = @tag.projects.order('created_at DESC')
    end
    

    def edit
    end
    
    def get_tags
      @sass_tags = Tag.all_sass
      @mobile_tags = Tag.all_mobile
      @website_tags = Tag.all_websites
      @agency_tags = Tag.all_agencies
      @startup_tags = Tag.all_startups
    end
    
    private
    def tag_params
      params.require(:tag).permit(:name)
    end
    
    
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").limit(4)
  end
  
  def about
  end
  
  def missing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<div class="container">
    <h1> Request quote</h1>
    <div>
        <h2>Thank you for your message</h2>
        <p>I will get back to you soon</p>
    </div>
</div>

app/views/layouts/_about_header.html.erb
<div class="header-wrapper header-wrapper-about">
        <!-- ******HEADER****** --> 
        <header id="header" class="header navbar-fixed-top">  
            <div class="container">       
                <h1 class="logo">
                    <a href="index.html"><span class="highlight">Dev</span>Studio</a>
                </h1><!--//logo-->
                <nav class="main-nav navbar-right" role="navigation">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button><!--//nav-toggle-->
                    </div><!--//navbar-header-->
                    <div id="navbar-collapse" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="nav-item"><%= link_to "Home", root_path %></li>
                            <li class="nav-item"><%= link_to "Projects", projects_path %></li>
                            <li class="active nav-item"><%= link_to "About", about_path %></li>                                              
                            <li class="nav-item"><%= link_to "Blog", posts_path %></li>
                            <li class="nav-item last"><%= link_to "Contact", new_contact_path %></li>
                        </ul><!--//nav-->
                    </div><!--//navabr-collapse-->
                </nav><!--//main-nav-->
            </div><!--//container-->
        </header><!--//header-->   
        <section class="promo section">
            <div class="container text-center">                
                <h2 class="title">About Us</h2>
                <p class="intro">We believe rhoncus lectus vehicula fermentum tincidunt. Nunc tincidunt felis pulvinar, mollis sapien ac, malesuada ante</p>
            </div><!--//container-->
        </section><!--//promo-->
    </div>

app/views/layouts/_blog_header.html.erb
<div class="header-wrapper header-wrapper-blog-home">
        <!-- ******HEADER****** --> 
        <header id="header" class="header navbar-fixed-top">  
            <div class="container">       
                <h1 class="logo">
                    <a href="index.html"><span class="highlight">Dev</span>Studio</a>
                </h1><!--//logo-->
                <nav class="main-nav navbar-right" role="navigation">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button><!--//nav-toggle-->
                    </div><!--//navbar-header-->
                    <div id="navbar-collapse" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="nav-item"><%= link_to "Home", root_path %></li>
                            <li class="nav-item"><%= link_to "Projects", projects_path %></li>
                            <li class="nav-item"><%= link_to "About", about_path %></li>                                              
                            <li class="active nav-item"><%= link_to "Blog", posts_path %></li>
                            <li class="nav-item last"><%= link_to "Contact", new_contact_path %></li>
                        </ul><!--//nav-->
                    </div><!--//navabr-collapse-->
                </nav><!--//main-nav-->
            </div><!--//container-->
        </header><!--//header-->   
        <section class="promo section">
            <div class="container text-center">                
                <h2 class="title">Blog</h2>
                <p class="intro">Lorem ipsum dolor sit amet consectetuer adipiscing elit massa sociis natoque penatibus et magnis dis parturient montes</p>
            </div><!--//container-->
        </section><!--//promo-->
    </div>

app/views/layouts/_contact_header.html.erb
<div class="header-wrapper header-wrapper-contact">
        <!-- ******HEADER****** --> 
        <header id="header" class="header navbar-fixed-top">  
            <div class="container">       
                <h1 class="logo">
                    <a href="index.html"><span class="highlight">Dev</span>Studio</a>
                </h1><!--//logo-->
                <nav class="main-nav navbar-right" role="navigation">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button><!--//nav-toggle-->
                    </div><!--//navbar-header-->
                    <div id="navbar-collapse" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="nav-item"><%= link_to "Home", root_path %></li>
                            <li class="nav-item"><%= link_to "Projects", projects_path %></li>
                            <li class="nav-item"><%= link_to "About", about_path %></li>                                              
                            <li class="nav-item"><%= link_to "Blog", posts_path %></li>
                            <li class="active nav-item last"><%= link_to "Contact", new_contact_path %></li>
                        </ul><!--//nav-->
                    </div><!--//navabr-collapse-->
                </nav><!--//main-nav-->
            </div><!--//container-->
        </header><!--//header-->   
        <section class="promo section">
            <div class="container text-center">                
                <h2 class="title">Contact Us</h2>
                <p class="intro">Get in touch if you have a project or want to find out more about our services. We'd love to hear from you!</p>
            </div><!--//container-->
        </section><!--//promo-->
    </div>

app/views/layouts/_header.html.erb
<header id="header" class="header navbar-fixed-top">  
        <div class="container">       
            <h1 class="logo">
                <a href="index.html"><span class="highlight">Dev</span>Studio</a>
            </h1><!--//logo-->
            <nav class="main-nav navbar-right" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><!--//nav-toggle-->
                </div><!--//navbar-header-->
                <div id="navbar-collapse" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="nav-item"><%= link_to "Home", root_path %></li>
                        <li class="nav-item"><%= link_to "Projects", projects_path %></li>
                        <li class="nav-item"><%= link_to "About", about_path %></li>                                              
                        <li class="nav-item"><%= link_to "Blog", posts_path %></li>
                        <li class="nav-item last"><%= link_to "Contact", new_contact_path %></li>
                    </ul><!--//nav-->
                </div><!--//navabr-collapse-->
            </nav><!--//main-nav-->
        </div><!--//container-->
    </header>

app/views/layouts/_homeheader.html.erb
<div class="header-wrapper header-wrapper-home">
        <!-- ******HEADER****** --> 
        <header id="header" class="header navbar-fixed-top header-shrink">  
            <div class="container">       
                <h1 class="logo">
                    <a href="index.html"><span class="highlight">Dev</span>Studio</a>
                </h1><!--//logo-->
                <nav class="main-nav navbar-right" role="navigation">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button><!--//nav-toggle-->
                    </div><!--//navbar-header-->
                    <div id="navbar-collapse" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="active nav-item"><%= link_to "Home", root_path %></li>
                            <li class="nav-item"><%= link_to "Projects", projects_path %></li>
                            <li class="nav-item"><%= link_to "About", about_path %></li>                                              
                            <li class="nav-item"><%= link_to "Blog", posts_path %></li>
                            <li class="nav-item last"><%= link_to "Contact", new_contact_path %></li>
                        </ul><!--//nav-->
                    </div><!--//navabr-collapse-->
                </nav><!--//main-nav-->
            </div><!--//container-->
        </header><!--//header-->   
        <div class="bg-slider-wrapper">
            <div id="bg-slider" class="flexslider bg-slider">
                <ul class="slides">
                    <li class="slide slide-1 flex-active-slide" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 1; display: block; z-index: 2;"></li>
                    <li class="slide slide-2" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;"></li>
                    <li class="slide slide-3" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;"></li>
                </ul>
            </div>
        </div><!--//bg-slider-wrapper--> 
        <section id="home-promo" class="home-promo section">
            <div class="container text-center">                
                <h2 class="title">
                    <span class="upper">We build</span>
                    <span class="middle">Web and Mobile Apps</span>
                    <span class="bottom">for startups and agencies</span>
                </h2>
                <button class="btn btn-cta btn-cta-primary" type="button" data-toggle="modal" data-target="#modal-contact" data-backdrop="static">Talk to us</button>
            </div><!--//container-->
        </section><!--//promo-->
</div>

app/views/layouts/_work_header.html.erb
<div class="header-wrapper header-wrapper-work">
        <!-- ******HEADER****** --> 
        <header id="header" class="header navbar-fixed-top">  
            <div class="container">       
                <h1 class="logo">
                    <a href="index.html"><span class="highlight">Dev</span>Studio</a>
                </h1><!--//logo-->
                <nav class="main-nav navbar-right" role="navigation">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button><!--//nav-toggle-->
                    </div><!--//navbar-header-->
                    <div id="navbar-collapse" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="nav-item"><%= link_to "Home", root_path %></li>
                            <li class="active nav-item"><%= link_to "Projects", projects_path %></li>
                            <li class="nav-item"><%= link_to "About", about_path %></li>                                              
                            <li class="nav-item"><%= link_to "Blog", posts_path %></li>
                            <li class="nav-item last"><%= link_to "Contact", new_contact_path %></li>
                        </ul><!--//nav-->
                    </div><!--//navabr-collapse-->
                </nav><!--//main-nav-->
            </div><!--//container-->
        </header><!--//header-->   
        <section class="promo section">
            <div class="container text-center">                
                <h2 class="title">Our Work</h2>
                <p class="intro">Our approach to lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi in leo turpis. Ut ex neque, cursus vulputate facilisis sed, tempor quis ligula.</p>
            </div><!--//container-->
        </section><!--//promo-->
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <link href='//fonts.googleapis.com/css?family=Merriweather+Sans:700,300italic,400italic,700italic,300,400' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Russo+One' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if @title == "home" %>
    <%= render "layouts/homeheader" %>
  <% elsif @title == "blog" %>
    <%= render "layouts/blog_header" %>
  <% elsif @title == "About" %>
    <%= render "layouts/about_header" %>
  <% elsif @title == "Contact" %>
    <%= render "layouts/contact_header" %>
  <% elsif @title == "Projects" %>
    <%= render "layouts/work_header" %>
  <% else %>
    <%= render "layouts/header" %>
  <% end %>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

  <%= render "layouts/home_footer" %>
   <!-- Main Javascript -->   
   
    <%= javascript_include_tag 'jquery-1.11.3.min' %>
    <%= javascript_include_tag 'back-to-top' %>        
    <%= javascript_include_tag 'jquery.placeholder' %>                                                                  
    <%= javascript_include_tag 'jquery.matchHeight-min' %>
    <%= javascript_include_tag 'jquery.fitvids' %>
    <%= javascript_include_tag 'main' %>
    <%= javascript_include_tag 'application' %>
    
    <% if @title == "home" %>
    <!-- Flexslider -->    
    <%= javascript_include_tag 'jquery-1.11.3.min' %>
    <%= javascript_include_tag 'jquery.flexslider-min' %>     
    <%= javascript_include_tag 'flexslider-custom' %>
    <% end %>
    
    <% if @title == "Contact" %>
    <!-- Form Validation -->
    <%= javascript_include_tag 'jquery.validate.min' %> 
    <%= javascript_include_tag 'form-validation-custom' %>
    <% end %>
    
    <!-- Form iOS fix -->
    <%= javascript_include_tag 'isMobile.min' %>
    <%= javascript_include_tag 'form-mobile-fix' %>
    
    <% if @title == "home" %>
    <!-- Owl Carousel -->
    <%= javascript_include_tag 'owl.carousel' %>
    <%= javascript_include_tag 'owl-custom' %>
    <% end %>

    <%= javascript_include_tag 'imagesloaded.pkgd.min' %>
    <%= javascript_include_tag 'isotope.pkgd.min' %>
    <%= javascript_include_tag 'isotope-custom' %>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'trendprowebsite';
    var disqus_identifier = '<%= @post.id %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
    <%= f.file_field :image %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category" }, input_html: { class: "dropdown-toggle" } %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
    </div>
    
    <%= f.submit "Create Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving</h2>
    <% end %>
    <ul>
        <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    
    <%= f.file_field :image %>
    <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :category %><br>
        <%= f.text_field :category, placeholder: "example: SAAS / STARTUP" %>
    </div>
    
    <strong>Tags:</strong>
        <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |cb| %>
        <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
        <br><br>
    
    <div class="form-group">
        <%= f.label :client %><br>
        <%= f.text_field :client, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :work_done %><br>
        <%= f.text_area :work_done, class: "form-control" %>
    </div>
    
  
    <div class="form-group">
        <%= f.label :link %><br>
        <%= f.text_field :link, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :challenge %><br>
        <%= f.text_area :challenge, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :project_goals %><br>
        <%= f.text_area :project_goals, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :solution %><br>
        <%= f.text_area :solution, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :results %><br>
        <%= f.text_area :results, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :client_testimonial %><br>
        <%= f.text_area :client_testimonial, class: "form-control" %>
    </div>
    
    <%= f.submit "Create project", class: "btn btn-primary" %>
    
<% end %>

app/views/projects/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/tags/index.html.erb
<% @mobile_tags.each do |tag| %>
<option id="<%= tag.id %>"><%= tag.name %></option%>
<% end %>

app/views/tags/new.html.erb
<div class="container">
    <div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @tag do |f| %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <br>
        
        <%= f.submit "Create tag", class: "btn btn-success" %>
        <% end %>
    </div>
    </div>
</div>

app/views/welcome/about.html.erb
<% @title = "About" %>
<section class="join-us section">
    <div class="container">
        <h2 class="title text-center">Join Our Team</h2>
        <p class="intro text-center">We love what we do vestibulum tincidunt tincidunt nisl et consectetur mauris sed dui non sapien rhoncus volutpat pellentesque</p>
        <div class="row">
            <div class="info col-md-7 col-sm-6 col-xs-12">
                <p>You can use this section to advertise jobs or attract freelancers to join your team... Fringilla potenti morbi sociosqu dignissim sociis ridiculus. Magna parturient. Auctor convallis. Elementum adipiscing est. Rutrum. Viverra hac congue aliquam accumsan nam laoreet ut nascetur eu vulputate diam. Lacinia placerat ad lectus. Phasellus sit enim, metus quam hymenaeos fringilla venenatis natoque.</p>
                <p>Sollicitudin hendrerit facilisis. Pretium quisque blandit justo massa condimentum varius lobortis, hymenaeos nec phasellus lectus Convallis convallis magnis pellentesque blandit Molestie sociosqu pede.</p>
                
                <p>If you are an iOS/Android developer interested in joining our team, please email your CV to <a href="#">jobs@devstudio.com</a></p>
            </div>
            <div class="partner col-md-4 col-sm-5 col-xs-12 col-md-push-1 col-sm-push-1 col-xs-push-0">
                <h3 class="sub-title">Want to partner with us?</h3>
                <p>If you are a development focused team you might want to attract design partners here...Vulputate sed Nostra elit consequat penatibus. Hac habitant inceptos scelerisque tempor dis purus orci. Risus porta. Arcu gravida, cubilia taciti, ultricies Nisi posuere magna penatibus non suspendisse in mus hendrerit.</p>
                <%= link_to "Contact us today!", new_contact_path, class:"btn btn-cta btn-cta-primary" %>
            </div><!--//partner-->
        </div><!--//row-->
    </div><!--//row-->
</section>
<section id="cta-section" class="cta-section section text-center home-cta-section">
    <div class="container">
       <h2 class="title">Want to have a quick chat?</h2>
       <p class="phone contact-info">
           <span class="intro">We are only a phone call away</span>
           <span class="info"><a href="tel:+08001234567">0800 123 4567</a></span>
       </p><!--//phone-->
       <p class="email contact-info">
           <span class="intro">You can also email us</span>
           <span class="info"><a href="mailto:hello@yourdevstudio.com">hello@yourdevstudio.com</a></span>
       </p><!--//phone-->              
    </div><!--//container-->
</section>